matrix:
  include:
    - os: osx
      osx_image: xcode11.4
      language: node_js
      node_js: "14"
      env:
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

    # Windows currently doesn't support encrypted variables.
    # Once supported uncomment this out & remove build with Docker
    #
    #- os: windows
    #  language: node_js
    #  node_js: "10"

    - os: linux
      services: docker
      language: generic

cache:
  yarn: true
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

script:
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      docker run --rm \
        -e GH_TOKEN=$GH_TOKEN \
        -v $PWD:/project \
        -v ~/.cache/electron:/root/.cache/electron \
        -v ~/.cache/electron-builder:/root/.cache/electron-builder \
        electronuserland/builder:wine \
        /bin/bash -c "yarn --link-duplicates --pure-lockfile && yarn run app:deploy:win"
    elif [ "$TRAVIS_OS_NAME" == "windows" ]; then
      yarn;
      yarn run app:deploy:win;
    else
      # security create-keychain -p $MAC_KEYCHAIN_PASSWORD build.keychain;
      # security default-keychain -s build.keychain;
      # security unlock-keychain -p $MAC_KEYCHAIN_PASSWORD build.keychain;
      # echo $MAC_DEVELOPER_CERT | base64 --decode - > keystore.p12;
      # security import keystore.p12 -k build.keychain -P $MAC_KEYCHAIN_PASSWORD -T /usr/bin/codesign;
      # security set-key-partition-list -S apple-tool:,apple: -s -k $MAC_KEYCHAIN_PASSWORD build.keychain;
      yarn;
      yarn run app:deploy:mac;
    fi
before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine
branches:
  only:
  - master
